name: shada_banking
description: Shada mobile banking zoomrad.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  lottie: 2.2.0
  localization: ^2.1.0
  floating_bottom_navigation_bar: ^1.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
